spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/modular_bank
    username: ${DB_USER:bank}
    password: ${DB_PASSWORD:bank}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

jwt:
  secret: ${JWT_SECRET:modular-bank-dev-secret-change-in-production-256bit}
  access-expiration-minutes: 80
  refresh-expiration-days: 7

finbank:
  kafka:
    topics:
      notifications: notification-events

server:
  port: 8081
